export const propositions = [
  "The cup is made of paper",
  "The grass is wet",
  "The dog was walked an hour ago",
  "There is milk in the refrigerator",
  "The book on the shelf is red",
  "The car has a full tank of gas",
  "The doorbell just rang",
  "The temperature is below freezing",
  "The computer is turned on",
  "The baby is sleeping",
  "There are four chairs at the dining table",
  "The TV remote control is missing",
  "The phone battery is fully charged",
  "The traffic light just turned green",
  "The cake is delicious",
  "The music is playing softly",
  "The window is open",
  "The shoes are brand new",
  "The clock is ticking",
  "The coffee is hot",
  "The printer is out of ink",
  "The pen is blue",
  "The vase is made of glass",
  "The grocery store is closed on Sundays",
  "The painting on the wall is a Picasso",
  "The street is crowded with people",
  "The alarm will go off in five minutes",
  "The tree is shedding leaves",
  "The email was sent three hours ago",
  "The soccer game ended in a tie",
  "The movie starts at 7:00 pm.",
  "The restaurant serves vegetarian options",
  "The air conditioner is set to 72 degrees",
  "The battery is low",
  "The book has 300 pages",
  "The train is running late",
  "The building is five stories tall",
  "The rain will stop by noon",
  "The shirt is made of cotton",
  "The bus arrived on time",
  "The mirror is cracked",
  "The museum is closed on Mondays",
  "The necklace is made of silver",
  "The ice cream is melting",
  "The shoes are a size 9",
  "The computer program is running smoothly",
  "The suitcase weighs 20 kilograms",
  "The flowers are in bloom",
  "The phone is on vibrate mode",
  "The textbook is written in English",
  "The basketball hoop is 10 feet high",
  "The tea is steeping",
  "The medicine expires next month",
  "The streetlights are flickering",
  "The DVD is scratched",
  "The bridge is under construction",
  "The coffee shop offers free Wi-Fi",
  "The painting is hanging slightly crooked",
  "The soccer field is waterlogged",
  "The email attachment is a PDF file",
  "The concert tickets are sold out",
  "The car's tire pressure is low",
  "The grocery store is having a sale on fruits",
  "The laptop has a cracked screen",
  "The meeting will start in 15 minutes",
  "The pizza delivery will arrive in 30 minutes",
  "The street is blocked due to a parade",
  "The faucet is leaking",
  "The cookies are freshly baked",
  "The museum exhibit is interactive",
  "The shirt needs to be ironed",
  "The movie is based on a true story",
  "The suitcase has a broken zipper",
  "The flowers need to be watered",
  "The phone has a full battery",
  "The bookshelf is organized by genre",
  "The car's engine is overheating",
  "The painting is a landscape scene",
  "The milk carton is half full",
  "The clock is ticking backwards",
  "The computer has a virus",
  "The traffic jam is causing delays",
  "The coffee mug is chipped",
  "The prescription needs to be refilled",
  "The street sign is missing",
  "The necklace is a family heirloom",
  "The ice cream parlor has 31 flavors",
  "The shoes are scuffed",
  "The printer is out of paper",
  "The pen has black ink",
  "The vase is filled with fresh flowers",
  "The dog is barking loudly",
  "The playground is busy with children playing",
  "The TV show is in its final season",
  "The grocery store aisle is crowded",
  "The phone has a cracked screen protector",
];
export const factPrefixes =
  "Take the following text and prefix each assertion with '\n[FACT]' or '\n[OPINION]' (break up sentences if necessary):";

export const replacePronouns =
  "Take the following text and replace each pronoun with its referent.";
